version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
    cooldown:
      default-days: 5
      semver-minor-days: 7
      semver-patch-days: 3
