# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
  amd64: ghcr.io/home-assistant/amd64-base:3.21
  armhf: ghcr.io/home-assistant/armhf-base:3.21
  armv7: ghcr.io/home-assistant/armv7-base:3.21
  i386: ghcr.io/home-assistant/i386-base:3.21
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Gitea add-on"
  org.opencontainers.image.description: "Gitea add-on for self hosted repositories in Home Assistant"
  org.opencontainers.image.source: "https://github.com/jmichelp/ha-addon-gitea"
  org.opencontainers.image.licenses: "Apache 2.0"

args:
  TEMPIO_VERSION: "2024.11.2"
  GITEA_VERSION: "1.23.8"

