# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Gitea add-on
version: "0.0.1"
slug: gitea
description: Gitea add-on for self-hosted code repositories
url: "https://github.com/jmichelp/ha-addon-gitea/tree/main/gitea"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
ports:
  22/tcp: 3022
  3000/tcp: 3000
ports_description:
  22/tcp: "Git SSH Interface"
  3000/tcp: "Gitea Web Interface"
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]/"
panel_icon: "mdi:mdi-git"
panel_title: "Gitea"
map:
  - ssl:rw
image: "ghcr.io/jmichelp/{arch}-addon-gitea"
