# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Gitea add-on
version: "0.0.8"
slug: gitea
description: Gitea add-on for self-hosted code repositories
url: "https://github.com/jmichelp/ha-addon-gitea/tree/main/gitea"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  ssl: false
  domain: homeassistant.local
  use_nginx: true
schema:
  ssl: bool
  domain: match(^[a-z0-9-.]{1,253}$)
  root_url: str?
  use_nginx: bool
ingress: true
ingress_port: 3000
services:
  mysql:want
ports:
  22/tcp: 3022
  3000/tcp: 3000
ports_description:
  22/tcp: "Git SSH Interface"
  3000/tcp: "Gitea Web Interface"
# webui: "http://[HOST]:[PORT:3000]/"
panel_icon: "mdi:mdi-git"
panel_title: "Gitea"
map:
  - share:rw
  - ssl:ro
image: "ghcr.io/jmichelp/{arch}-addon-gitea"
stage: experimental
